on:
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: Test app
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: ci
      POSTGRES_PASSWORD:  ${{ secrets.POSTGRES_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - run: pip install poetry
      - run: poetry config virtualenvs.create false && poetry install --no-root --no-interaction --no-ansi
      - run: docker compose build
      - run: docker compose up -d --build
      - run: sleep 10
      - run: pytest tests --junit-xml=test-results.xml
        env:
          APP_URL: http://127.0.0.1:8081

      - run: docker compose logs app
        if: always()

      - name: Surface failing tests
        if: always()
        uses: pmeier/pytest-results-action@main
        with:
          path: test-results.xml
          summary: true
          display-options: fEX
          fail-on-empty: true
          title: Test results
